### ISSUE TITLE
I've been trying to use this code

### ISSUE THREAD

**Issue by TakesTheBiscuit** [regan-karlewicz/yfinance2pg#1]
Hi

_Feels bad taking up /issues/1 with this but here goes_

I came up with an horrendous hack a few weeks back, i made a 'demo.py' script inside:

```
import yfinance2pg as yf2pg

yf2pg.start()
```

I was then calling this script from terminal:
```
$ python demo.py
```

I know this isn't the right way to use this repo.

Could you document how to get up and running? - sorry i am sure i've missed something obvious but i can't see what it is?

**Comment by TakesTheBiscuit** [comment]
This also works:
```
import yfinance2pg.tickers as y2
ticks = y2.get_sec_list()
print(ticks)
```

But i think i'm supposed to be able to just call `yfinance2pg` from a terminal and have it deal with accepting params, seems like i've just missed something - probably python itself confusing me.

**Comment by regan-karlewicz** [comment]
Hi @TakesTheBiscuit 

Sorry for taking so long to get back to you. I've added the install command in the README. Let me know if this doesn't work for you.
